// Generated by scripts/extract-hero-frames.mjs — do not edit by hand.
export const HERO_FRAMES = {
  width: 768,
  height: 922,
  cols: 8,
  count: 48,
  sheet: "/hero/frames.webp",
  poster: "/hero/poster.webp",
} as const;
